"""Tests for the RUL formula baseline (Tier-0 item #2).

The formula baseline answers the question the SOH trivial baseline can't:
the RUL target for cells that never reach EOL in-window is GENERATED by a
closed form. `rul_formula_baseline_lco()` reproduces that closed form under
identical LCO folds, so "did the model beat the formula?" is measurable —
and on extrapolated-label rows the formula is an identity (R² = 1) by
construction, which these tests also pin.
"""

from conftest import make_cycles_df
from batlab.validation.trivial_baseline import rul_formula_baseline_lco
from batlab.validation.lco import run_lco


def _slow_fleet():
    """Cells that never reach EOL in-window → 100% extrapolated labels."""
    return {
        f"Cell{i}": make_cycles_df(n_cycles=300, fade_per_cycle=0.0002 + i * 1e-5)
        for i in range(3)
    }


def test_formula_is_identity_on_extrapolated_rows():
    """On formula-generated labels, the formula must score R² = 1 — pinning
    exactly how much of the old mixed-pool R² was formula recovery."""
    result = rul_formula_baseline_lco(_slow_fleet())
    assert result["rul_baseline_pool"] == "extrapolated"
    assert result["rul_formula_baseline_r2_extrapolated"] is not None
    assert result["rul_formula_baseline_r2_extrapolated"] > 0.99


def test_headline_follows_run_lco_pool_convention():
    """The baseline's headline pool convention matches run_lco()'s: observed
    pool when any fold has observed rows, otherwise the extrapolated pool —
    with the pool NAMED so one is never mistaken for the other."""
    result = rul_formula_baseline_lco(_slow_fleet())
    assert result["rul_baseline_pool"] == "extrapolated"
    assert result["rul_formula_baseline_r2"] == result["rul_formula_baseline_r2_extrapolated"]

    observed_fleet = {
        f"Cell{i}": make_cycles_df(n_cycles=300, fade_per_cycle=0.003 + i * 0.0005)
        for i in range(3)
    }
    result_obs = rul_formula_baseline_lco(observed_fleet)
    assert result_obs["rul_baseline_pool"] == "observed"
    assert result_obs["rul_formula_baseline_r2"] == result_obs["rul_formula_baseline_r2_observed"]


def test_baseline_uses_the_same_folds_as_run_lco():
    """Fold structure must mirror run_lco()'s — same held-out cells, same
    per-cell population — so model-vs-formula is apples-to-apples."""
    fleet = _slow_fleet()
    baseline = rul_formula_baseline_lco(fleet)
    model = run_lco(fleet)
    assert set(baseline["per_cell"].keys()) == set(model["per_cell"].keys())
    assert baseline["n_cells"] == len(fleet)


def test_single_cell_pool_is_empty_not_fabricated():
    result = rul_formula_baseline_lco({"Only": make_cycles_df()})
    assert result["per_cell"] == {}
    assert result["rul_formula_baseline_r2"] is None
    assert result["rul_baseline_pool"] == "none"


def test_formula_baseline_on_observed_rows_beatable_by_model():
    """Sanity: on a fast-fade fleet (observed EOL), the closed form is NOT an
    identity — it produces finite, sub-1 R² that a real model can be compared
    against."""
    fleet = {
        f"Cell{i}": make_cycles_df(n_cycles=300, fade_per_cycle=0.003 + i * 0.0005)
        for i in range(3)
    }
    result = rul_formula_baseline_lco(fleet)
    assert result["rul_baseline_pool"] == "observed"
    r2 = result["rul_formula_baseline_r2"]
    assert r2 is not None and r2 == r2  # finite
    assert r2 < 1.0
