from pages.login           import render_login
from pages.overview        import page_overview
from pages.health          import page_health
from pages.insights        import page_insights
from pages.fleet           import page_fleet
from pages.compare         import page_compare
from pages.grading         import page_grading
from pages.passport        import page_passport
from pages.reports         import page_reports
from pages.recommendations import page_recommendations
from pages.consequences    import page_consequences
from pages.sustainability  import page_sustainability
from pages.copilot         import page_copilot
from pages.import_page     import page_import
from pages.settings        import page_settings
