"""Mechanical leakage lint for target/feature relationships.

Why this exists
---------------
The single most misleading number this platform ever reported — Severson RUL
R² = 0.9994 — was not a modelling failure but an evaluation-arithmetic
failure: for cells that never reach EOL in-window, the RUL label is
GENERATED by the closed form

    rul = (capacity_ah − eol_capacity) / fade_rate_50cy

and `fade_rate_50cy` is itself FEATURE_COLUMNS entry #3. The model was handed
the denominator of the expression that produced its own target, so a
near-perfect R² there is an identity, not skill. That was found by an audit,
by hand. This module makes the same class of defect impossible to reintroduce
silently: it mechanically inspects the label-generating expressions in
batlab.features.engineering and fails when any quantity the expression
consumes is also a model feature.

The lint is deliberately narrow and mechanical — it does not try to prove
causal innocence of every feature; it asserts the two invariants we can
check exactly:

  1. Label-formula isolation: no variable read by the RUL label's
     generating expressions (both branches) appears in FEATURE_COLUMNS.
  2. Provenance coverage: rul_label_kind exists in build_features() output
     and distinguishes the two branches, so the observed/extrapolated split
     run_lco() relies on cannot silently disappear.

Run via tests/test_leakage_lint.py (CI) or directly:
    python -m batlab.validation.leakage_lint
"""

from __future__ import annotations

import ast
import inspect
import textwrap
from pathlib import Path

from batlab.features.engineering import FEATURE_COLUMNS, TARGET_RUL, TARGET_SOH

# The two variables the RUL target's extrapolated branch reads (see the
# "── RUL target ──" block in build_features()). Kept as explicit constants —
# listing them here is the audit trail; deriving them by parsing alone would
# make the lint silently pass if the code shape changed under it.
RUL_FORMULA_VARS = ("capacity_ah", "eol_capacity", "fade_rate_50cy")

# Model features that are LEGITIMATE inputs to the label expression because
# the label for their rows is measured, not generated by the formula.
# (Currently empty: fade_rate_50cy is NOT exempt — it is the leak.)
RUL_FORMULA_EXEMPTIONS: frozenset[str] = frozenset()


def _engineering_source() -> str:
    path = Path(inspect.getfile(_engineering_module()))
    return path.read_text(encoding="utf-8")


def _engineering_module():
    import batlab.features.engineering as mod
    return mod


def _assigned_names(expr: ast.AST) -> set[str]:
    """Every data quantity read inside an expression: plain Name loads
    (e.g. `eol_capacity`) AND df["column"] subscript strings (e.g.
    `"capacity_ah"` from `df["capacity_ah"]`) — the latter are Constants,
    not Names, and the RUL formula reads its inputs as df columns."""
    names: set[str] = set()
    for node in ast.walk(expr):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
            names.add(node.id)
        elif (
            isinstance(node, ast.Subscript)
            and isinstance(node.value, ast.Name)
            and node.value.id == "df"
            and isinstance(node.slice, ast.Constant)
            and isinstance(node.slice.value, str)
        ):
            names.add(node.slice.value)
    return names


def rul_label_expression_vars() -> dict:
    """Parse build_features()'s source and extract every data quantity the
    RUL label branches read — directly in the df["rul"] expressions AND via
    intermediate locals (the extrapolated branch computes `fade_rate` from
    df["fade_rate_50cy"] before using it, so the read-set must span the
    whole branch, not just the final assignment).

    Returns {"observed": {names...}, "extrapolated": {names...}, "found": bool}
    — both branches merged into each set (the lint's invariant is about the
    union: no formula input may be a feature).
    """
    src = textwrap.dedent(_engineering_source())
    tree = ast.parse(src)
    read_set: set = set()
    found = False

    def _assigns_rul(stmt) -> bool:
        return (
            isinstance(stmt, ast.Assign)
            and len(stmt.targets) == 1
            and isinstance(stmt.targets[0], ast.Subscript)
            and isinstance(stmt.targets[0].value, ast.Name)
            and stmt.targets[0].value.id == "df"
            and isinstance(stmt.targets[0].slice, ast.Constant)
            and stmt.targets[0].slice.value == TARGET_RUL
        )

    for node in ast.walk(tree):
        if not isinstance(node, ast.If):
            continue
        # A branch (if-body or else-body) that assigns df["rul"]: collect
        # every quantity read by ANY statement in that branch, so
        # intermediate locals like `fade_rate` resolve to their df-column
        # source (df["fade_rate_50cy"]).
        for branch in (node.body, node.orelse):
            # ast.walk() takes a single node, not a list of statements.
            has_rul = any(
                _assigns_rul(stmt)
                for stmt in branch
                if isinstance(stmt, ast.Assign)
            ) or any(
                _assigns_rul(inner)
                for stmt in branch
                for inner in ast.walk(stmt)
                if isinstance(inner, ast.Assign)
            )
            if not has_rul:
                continue
            found = True
            for stmt in branch:
                if isinstance(stmt, ast.Assign):
                    read_set |= _assigned_names(stmt.value)

    return {"observed": set(read_set), "extrapolated": set(read_set), "found": found}


def check_rul_formula_isolation() -> list[str]:
    """Invariant 1: no variable the RUL label expression reads may be a model
    feature (unless explicitly exempted). Returns a list of violations."""
    vars_read = rul_label_expression_vars()
    if not vars_read["found"]:
        return ["leakage_lint: could not locate the RUL label assignment in "
                "build_features() — the lint must be updated, not skipped."]

    violations = []
    for var in sorted(vars_read["observed"]):
        if var in RUL_FORMULA_VARS and var in FEATURE_COLUMNS and var not in RUL_FORMULA_EXEMPTIONS:
            violations.append(
                f"LEAK: '{var}' is read by the RUL label-generating expression "
                f"AND is FEATURE_COLUMNS[{FEATURE_COLUMNS.index(var)}]. A model "
                "trained on it is graded on recovering its own target's "
                "formula, not on forecasting degradation."
            )
    return violations


def check_label_provenance_coverage(featured_sample) -> list[str]:
    """Invariant 2: build_features() output must carry rul_label_kind so the
    observed/extrapolated split is checkable. `featured_sample` is a
    build_features() output DataFrame (any cell)."""
    violations = []
    if featured_sample is not None and "rul_label_kind" not in featured_sample.columns:
        violations.append(
            "LEAK-GUARD: build_features() output has no 'rul_label_kind' column — "
            "run_lco()'s observed/extrapolated split cannot be verified on this data."
        )
    elif featured_sample is not None:
        kinds = set(featured_sample["rul_label_kind"].unique())
        bad = kinds - {"observed", "extrapolated"}
        if bad:
            violations.append(
                f"LEAK-GUARD: rul_label_kind carries unexpected values {sorted(bad)} — "
                "the label provenance contract is 'observed' | 'extrapolated' only."
            )
    return violations


def run_lint(featured_sample=None) -> dict:
    """Run every check; returns {"ok": bool, "violations": [str, ...]}."""
    violations = list(check_rul_formula_isolation())
    violations += list(check_label_provenance_coverage(featured_sample))
    return {"ok": not violations, "violations": violations}


if __name__ == "__main__":  # pragma: no cover
    report = run_lint()
    for v in report["violations"]:
        print(v)
    raise SystemExit(0 if report["ok"] else 1)
