"""
Auto-generated model cards for logged training runs.

Every GBRT fit is logged automatically to the experiment registry
(src/experiment_registry.py) — dataset, chemistry, feature version, seed,
hyperparameters, leave-cell-out fold metrics, git commit, timestamp. A
model card is that record rendered as a structured, honest document, the
way ML practitioners expect a trained model to be described: model
identity, data provenance (including the dataset's license), validation
method and metrics, hyperparameters, reproducibility contract, and
limitations.

Two consumers:
  - The Benchmark page (app/_pages/benchmark.py) renders a card per run
    and offers the JSON for download.
  - The REST layer can attach a card fragment to a cell's health response
    (the run that produced that cell's model).

Honesty rules this module follows (same discipline as the rest of the
platform):
  - The license for a known public dataset comes from batlab.cite
    (the single source of truth for dataset license text); a synthetic
    fleet's card says it is internally generated; a tenant upload's card
    says the license is unknown and must be verified — no fabricated
    license text.
  - Cross-chemistry transfer runs ("X_to_Y") are explicitly marked NOT
    leave-cell-out in their limitations, matching experiment_registry.py's
    own notes field.
  - The replay contract is stated plainly: replay_run() re-trains with the
    CURRENT GBRT_PARAMS, so a card whose recorded hyperparams diverge from
    today's constants reports that divergence (hyperparams_match), never
    hides it.
"""

from __future__ import annotations

import json

# dataset key -> batlab.cite key for license resolution. Cross-chemistry
# runs are stripped to their training-domain prefix ("nasa_to_severson"
# -> "nasa") before lookup.
_DATASET_CITE_KEYS = {
    "nasa": "nasa",
    "severson": "severson2019",
    "oxford": "oxford2020",
    "calce": "calce",
    "zhu2022": "zhu2022",
}


def _base_dataset(dataset: str) -> str:
    """Training-domain key for a run's dataset field, stripping any
    cross-chemistry \"X_to_Y\" suffix."""
    return (dataset or "").split("_to_")[0]


def dataset_license(dataset: str) -> dict:
    """Resolve a run's dataset key to its license and provenance, honestly:
    known public datasets resolve through batlab.cite's own license text;
    the synthetic fleet is disclosed as internally generated (MIT code, no
    external data); a tenant upload has an unknown license that the card
    says must be verified rather than guessing one."""
    from batlab.cite import license_text

    base = _base_dataset(dataset)
    cite_key = _DATASET_CITE_KEYS.get(base)
    if cite_key is not None:
        return {"license": license_text(cite_key), "license_key": cite_key, "source": f"Public dataset (batlab.cite key '{cite_key}')."}
    if base == "synth":
        return {
            "license": "Internally generated synthetic fleet — MIT code, no external dataset redistributed.",
            "license_key": None,
            "source": "Generated by this platform's physics-informed synthetic battery generator.",
        }
    return {
        "license": "Unknown — user-provided/uploaded data. Verify the uploader's license before any redistribution.",
        "license_key": None,
        "source": "Tenant upload (raw cycles are never persisted — see src/bundle_cache.py).",
    }


def build_model_card(run: dict) -> dict:
    """Build a structured model card from one logged run dict (the shape
    experiment_registry.leaderboard()/db.load_experiment_runs() return).
    Every field is read from the record; nothing is invented here.

    The card is a plain JSON-serializable dict (no numpy types), so it can
    be downloaded as-is or rendered via model_card_markdown()."""
    fold_metrics = run.get("fold_metrics") or {}
    hyperparams = run.get("hyperparams") or {}
    license_info = dataset_license(run.get("dataset", ""))

    # Reproducibility: replay_run() trains with the CURRENT GBRT_PARAMS,
    # not the run's own logged snapshot. Recorded-vs-current divergence is
    # surfaced here (see experiment_registry.py's module docstring for why
    # this check exists at all).
    from batlab.validation.lco import GBRT_PARAMS as _CURRENT_GBRT_PARAMS
    hyperparams_diff = {
        k: (hyperparams.get(k), v)
        for k, v in _CURRENT_GBRT_PARAMS.items()
        if hyperparams.get(k) != v
    }

    return {
        "model": {
            "framework": "scikit-learn GradientBoostingRegressor — SOH point + RUL point + Q10/Q90 quantile models",
            "feature_version": run.get("feature_version"),
            "seed": run.get("seed"),
            "git_commit": run.get("git_commit"),
            "logged_at": run.get("timestamp"),
            "run_id": run.get("run_id"),
        },
        "dataset": {
            "key": run.get("dataset"),
            "chemistry": run.get("chemistry"),
            "n_cells": run.get("n_cells"),
            "n_rows": run.get("n_rows"),
            "cell_ids": run.get("cell_ids") or [],
            "features": run.get("feature_set") or [],
            "license": license_info["license"],
            "license_key": license_info["license_key"],
            "source": license_info["source"],
        },
        "validation": {
            "method": "Leave-Cell-Out (LCO) — train on N-1 cells, evaluate on the held-out cell; per-cell reliability floor RUL_RELIABLE_FLOOR = 0.3",
            "soh_mae": run.get("soh_mae"),
            "soh_r2": run.get("soh_r2"),
            "rul_mae": run.get("rul_mae"),
            "rul_r2": run.get("rul_r2"),
            "rul_reliable": bool(run.get("rul_reliable")),
            "n_folds": len(fold_metrics),
            "fold_metrics": fold_metrics,
        },
        "hyperparameters": hyperparams,
        "reproducibility": {
            "replay": "experiment_registry.replay_run() re-runs the recorded pipeline via evaluate_from_manifest (seed + feature_version guarded)",
            "hyperparams_match_current_gbrt_params": not hyperparams_diff,
            "hyperparams_diff_vs_current": hyperparams_diff,
        },
        "notes": run.get("notes"),
        "limitations": _LIMITATIONS(run),
    }


def _LIMITATIONS(run: dict) -> list:
    base = _base_dataset(run.get("dataset", ""))
    limitations = [
        "Validated on public laboratory datasets — generalization to a manufacturer's fleet is not claimed.",
        "Small LCO fold populations (e.g. NASA n=4) — reported metrics are estimates over few held-out cells, not certificates.",
        "RUL is cycles-to-EOL at the configured threshold (default 80% SOH) — not an arbitrary warranty floor.",
        "dQ/dV-derived features are physics simulations (OCV-polynomial), not measured curves (see METHODOLOGY §4).",
    ]
    if "_to_" in (run.get("dataset") or ""):
        limitations.append(
            "Cross-chemistry transfer run: a single train-on-all-of-one-domain / eval-on-all-of-the-other split, "
            "NOT leave-cell-out; metrics are reported honestly and never marked reliable."
        )
    if base == "synth":
        limitations.append("Trained on the platform's internally generated synthetic fleet — not a measurement of real cells.")
    return limitations


def model_card_markdown(card: dict) -> str:
    """Render a model card dict as readable Markdown (used by the Benchmark
    page's per-run expander). Sections mirror the card's structure."""
    m = card["model"]
    d = card["dataset"]
    v = card["validation"]
    rep = card["reproducibility"]

    lines = [
        f"### Model card — `{d['key']}`",
        "",
        f"**Model:** {m['framework']}",
        f"**Run ID:** {m.get('run_id') or '—'} · **Feature version:** {m.get('feature_version') or '—'} · "
        f"**Seed:** {m.get('seed')} · **Git commit:** {m.get('git_commit') or '—'} · **Logged:** {(m.get('logged_at') or '')[:19]}",
        "",
        "#### Data",
        f"**Chemistry:** {d.get('chemistry') or '—'} · **Cells:** {d.get('n_cells')} · **Rows:** {d.get('n_rows')}",
        f"**Cell IDs:** {', '.join(d['cell_ids']) or '—'}",
        f"**Features ({len(d['features'])}):** {', '.join(d['features']) or '—'}",
        f"**License:** {d['license']}",
        "",
        "#### Validation (Leave-Cell-Out)",
        f"**SOH** — MAE: {_fmt(v.get('soh_mae'))}% · R²: {_fmt(v.get('soh_r2'))}",
        f"**RUL** — MAE: {_fmt(v.get('rul_mae'), 1)} cycles · R²: {_fmt(v.get('rul_r2'))} · "
        f"Reliable: {'✓' if v.get('rul_reliable') else '—'} (per-cell floor 0.3)",
        f"**Folds:** {v.get('n_folds')}",
        "",
        "#### Hyperparameters",
        "`" + json.dumps(card.get("hyperparameters") or {}, indent=2, default=str) + "`",
        "",
        "#### Reproducibility",
        f"{rep.get('replay', '')}.",
        f"Recorded hyperparameters {'match' if rep.get('hyperparams_match_current_gbrt_params') else 'DIVERGE from'} the current GBRT_PARAMS"
        + (f" ({json.dumps(rep.get('hyperparams_diff_vs_current'), default=str)})" if rep.get("hyperparams_diff_vs_current") else ""),
        "",
        "#### Limitations",
    ]
    for lim in card.get("limitations") or []:
        lines.append(f"- {lim}")
    if card.get("notes"):
        lines += ["", f"**Notes:** {card['notes']}"]
    return "\n".join(lines)


def _fmt(v, decimals=3) -> str:
    return f"{v:.{decimals}f}" if v is not None else "—"
