from _pages.login           import render_login
from _pages.overview        import page_overview
from _pages.health          import page_health
from _pages.insights        import page_insights
from _pages.fleet           import page_fleet
from _pages.compare         import page_compare
from _pages.grading         import page_grading
from _pages.passport        import page_passport
from _pages.reports         import page_reports
from _pages.recommendations import page_recommendations
from _pages.consequences    import page_consequences
from _pages.sustainability  import page_sustainability
from _pages.copilot         import page_copilot
from _pages.import_page     import page_import
from _pages.settings        import page_settings
from _pages.compliance      import page_compliance
