"""Page: Health.

The Engineering Details tier (everything behind the "Engineering details"
checkbox below) lives in _health_diagnostics.py -- this file was 1,706
lines, the largest in app/_pages/, mixing the always-visible hero content
with ~1,280 lines of collapsible diagnostic expanders. page_health() keeps
the hero section (provenance, chemistry indicator, SOH cards, mechanism +
action cards, 12-month forecast) and delegates to
render_engineering_diagnostics() once the checkbox is on.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import streamlit as st
import pandas as pd
import plotly.graph_objects as go

from utils import (
    _action_bar, _md_html, base_layout, LEGEND_H,
    soh_status, _cell_provenance, _resample_df,
    render_card, metric_tile_html, cached_detect_knee,
)
from data_loader import CELL_STRESS_PROFILES
from design_system import provenance_banner, ACTION_META, CONF_META
from chemistry_profiles import ChemistryProfile
from _pages._health_diagnostics import render_engineering_diagnostics


# ---------------------------------------------------------------------------
# Page: Health
# ---------------------------------------------------------------------------

def page_health(df: pd.DataFrame, split_cycle: int, cell_id: str,
                bundle: dict = None, rul_reliable: bool = True, graph=None):
    _action_bar("health")
    st.markdown(f"# What is degrading {cell_id}?")
    _rdf = _resample_df(df)   # downsampled for charts; df still used for latest/masks

    # ── Data provenance declaration ──────────────────────────────────────────
    _cp = _cell_provenance(cell_id)
    _source_kind = ChemistryProfile.for_cell(cell_id).source_kind
    if _source_kind == "severson":
        _prov_detail = (
            f"Capacity and resistance data for <strong>{cell_id}</strong> are real measurements "
            f"from the Severson 2019 LFP dataset (Nature Energy, 2019). "
            f"Derived analyses (Resistance Component Proxy, rate capability) use physics models "
            f"applied to these measurements and are labelled ◐ SIMULATED individually. "
            f"dQ/dV analysis is not shown — the LiCoO₂ simulation is not applicable to LFP chemistry."
        )
    elif _source_kind == "oxford":
        _prov_detail = (
            f"Capacity data for <strong>{cell_id}</strong> are real measurements from the Oxford "
            f"Path-Dependent Battery Degradation Dataset (Raj et al., 2020) — sparse checkpoints, "
            f"not dense per-cycle data. Derived analyses on this page are not applicable to this "
            f"source; see Explore's Reference Datasets tab instead."
        )
    elif _cp == "measured":
        _prov_detail = (
            f"Capacity and resistance data for <strong>{cell_id}</strong> are real measurements "
            f"from the NASA PCoE Battery Aging Dataset (Saha &amp; Goebel, 2007). "
            f"Derived analyses (Resistance Proxy, dQ/dV, rate capability) use physics models applied to "
            f"these measurements and are labelled ◐ SIMULATED individually."
        )
    else:
        _prov_detail = (
            f"<strong>{cell_id}</strong> is a physics-informed synthetic cell generated by "
            f"<code>generate_cell_data()</code> — no physical measurements underlie any value "
            f"on this page. All analyses are labelled ○ SYNTHETIC. "
            f"<strong>Do not use synthetic cell outputs for real engineering decisions.</strong>"
        )
    _md_html(provenance_banner(_cp, _prov_detail))

    # ── Chemistry inline indicator ────────────────────────────────────────────
    _chem_label = {
        "severson":  "LFP · Lithium Iron Phosphate (Severson 2019)",
        "nasa":      "LiCoO₂ · Lithium Cobalt Oxide (NASA PCoE)",
        "synthetic": "LiCoO₂ · Lithium Cobalt Oxide (synthetic)",
        "uploaded":  "User-defined chemistry",
    }.get(st.session_state.get("data_mode", "synthetic"), "LiCoO₂")
    st.markdown(
        f"<div style='display:flex;align-items:center;gap:8px;margin-bottom:12px'>"
        f"<span style='font-size:10px;font-weight:700;background:#2d374899;"
        f"border:1px solid #4a5568;color:#a0aec0;padding:2px 9px;border-radius:6px;"
        f"letter-spacing:0.06em'>CHEMISTRY</span>"
        f"<span style='font-size:13px;color:#a0aec0'>{_chem_label}</span>"
        f"</div>",
        unsafe_allow_html=True,
    )

    latest = df.iloc[-1]
    current_soh = latest["soh_pct"]
    status_label, status_colour = soh_status(current_soh)

    # Knee-point detection
    knee = cached_detect_knee(df["soh_pct"], df["cycle_number"])
    sop_pct = float(latest["sop_pct"]) if "sop_pct" in latest.index else None

    knee_note = ""
    if knee["detected"]:
        k_cy  = knee["cycle"]
        k_soh = knee["soh_at_knee"]
        cur   = int(latest["cycle_number"])
        if cur >= k_cy:
            knee_note = f"· ⚡ Knee at cycle {k_cy} ({k_soh:.1f}% SOH) — now in accelerating phase"
        else:
            knee_note = f"· Knee projected ~cycle {k_cy} ({k_soh:.1f}% SOH)"

    _md_html(
        f"""
        <div class="hero-card">
            <div class="hero-label">Health Assessment · {cell_id}</div>
            <div class="hero-value {status_colour}">{current_soh:.1f}% SOH</div>
            <div class="hero-sub">
                Fading at ~{latest['fade_rate_50cy']*1000:.2f} mAh/cycle (50-cycle avg)
                &nbsp;·&nbsp; Internal resistance: {latest.get('resistance_ohm',0):.3f} Ω
                &nbsp;·&nbsp; Peak power: {f"{sop_pct:.0f}% of initial" if sop_pct else "—"}
                {knee_note}
            </div>
        </div>
        """
    )

    # ── C4: Pin baseline (Health page) ───────────────────────────────────────
    _h_pinned = st.session_state.get("pinned_cell")
    _h_pc2 = st.columns([8, 2])[1]
    with _h_pc2:
        if _h_pinned == cell_id:
            if st.button("📌 Unpin baseline", key=f"unpin_h_{cell_id}", use_container_width=True):
                import db as _db
                st.session_state["pinned_cell"] = None
                _db.set_setting(st.session_state["auth_org_id"], "pinned_cell", None)
                st.rerun()
        else:
            if st.button("📌 Pin as baseline", key=f"pin_h_{cell_id}", use_container_width=True,
                         help="Pin this cell as comparison baseline"):
                import db as _db
                st.session_state["pinned_cell"] = cell_id
                _db.set_setting(st.session_state["auth_org_id"], "pinned_cell", cell_id)
                st.rerun()

    col1, col2 = st.columns(2)

    # Anomaly cycles (precompute for both charts)
    cap_anomalies = df[df.get("capacity_anomaly", pd.Series(False, index=df.index))] if "capacity_anomaly" in df.columns else df.iloc[0:0]
    res_anomalies = df[df.get("resistance_anomaly", pd.Series(False, index=df.index))] if "resistance_anomaly" in df.columns else df.iloc[0:0]

    with col1:
        st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=_rdf["cycle_number"], y=_rdf["capacity_fade_ah"] * 1000,
            fill="tozeroy", fillcolor="rgba(252,129,129,0.08)",
            line=dict(color="#fc8181", width=2),
            hovertemplate="Cycle %{x}: %{y:.1f} mAh lost<extra></extra>",
            showlegend=False,
        ))
        if len(cap_anomalies) > 0:
            fig.add_trace(go.Scatter(
                x=cap_anomalies["cycle_number"],
                y=cap_anomalies["capacity_fade_ah"] * 1000,
                mode="markers", name=f"Anomaly ({len(cap_anomalies)})",
                marker=dict(color="#f6ad55", size=7, symbol="diamond",
                            line=dict(color="#1a202c", width=1)),
                hovertemplate="Cycle %{x}: anomalous capacity<extra>⚠ Anomaly</extra>",
            ))
        if knee["detected"]:
            fig.add_vline(x=knee["cycle"], line=dict(color="#9f7aea", width=1.5, dash="dot"),
                          annotation_text=f"Knee ({knee['cycle']})",
                          annotation=dict(font=dict(size=9, color="#9f7aea")))
        fig.update_layout(
            height=280,
            **base_layout(
                legend=LEGEND_H,
                xaxis=dict(title="Cycle", zeroline=False),
                yaxis=dict(title="mAh lost", zeroline=False),
            ),
        )
        st.plotly_chart(fig, use_container_width=True)
        _cap_lost_mah = float(_rdf["capacity_fade_ah"].iloc[-1]) * 1000
        _cap_caption = f"{_cap_lost_mah:.0f} mAh lost over {int(_rdf['cycle_number'].iloc[-1])} cycles — {knee['phase'].lower()} phase"
        if len(cap_anomalies) > 0:
            _cap_caption += f", {len(cap_anomalies)} anomalous cycle{'s' if len(cap_anomalies) != 1 else ''} flagged"
        st.caption(_cap_caption)

    with col2:
        st.markdown("<div style='height:4px'></div>", unsafe_allow_html=True)
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(
            x=_rdf["cycle_number"], y=_rdf["resistance_ohm"] * 1000,
            line=dict(color="#4a5568", width=1), name="Raw",
            hovertemplate="Cycle %{x}: %{y:.1f} mΩ<extra></extra>",
        ))
        fig2.add_trace(go.Scatter(
            x=_rdf["cycle_number"],
            y=_rdf["resistance_ohm"].rolling(30, min_periods=1).mean() * 1000,
            name="30-cycle avg", line=dict(color="#f6ad55", width=2),
            hovertemplate="Cycle %{x}: %{y:.1f} mΩ<extra>30-cy avg</extra>",
        ))
        if len(res_anomalies) > 0:
            fig2.add_trace(go.Scatter(
                x=res_anomalies["cycle_number"],
                y=res_anomalies["resistance_ohm"] * 1000,
                mode="markers", name=f"Spike ({len(res_anomalies)})",
                marker=dict(color="#fc8181", size=7, symbol="diamond",
                            line=dict(color="#1a202c", width=1)),
                hovertemplate="Cycle %{x}: resistance spike<extra>⚠ Spike</extra>",
            ))
        fig2.update_layout(
            **base_layout(
                height=280, legend=LEGEND_H,
                xaxis=dict(title="Cycle", zeroline=False),
                yaxis=dict(title="mΩ", zeroline=False),
            ),
        )
        st.plotly_chart(fig2, use_container_width=True)
        _res0 = float(_rdf["resistance_ohm"].iloc[0])
        _res_now = float(_rdf["resistance_ohm"].iloc[-1])
        _res_growth_pct = (_res_now / _res0 - 1) * 100 if _res0 > 0 else 0.0
        _res_trend_word = "growing" if _res_growth_pct > 5 else ("stable" if _res_growth_pct > -5 else "improving")
        _res_caption = f"{_res_trend_word.capitalize()} — {_res_growth_pct:+.0f}% vs. cycle 1"
        if len(res_anomalies) > 0:
            _res_caption += f", {len(res_anomalies)} spike{'s' if len(res_anomalies) != 1 else ''} flagged"
        st.caption(_res_caption)

    # ── Section 2: Mechanism (always visible) ───────────────────────────────
    _mech_v, _mech_c, _mech_icon = "Insufficient data", "#718096", "○"
    # Read from the shared Battery Knowledge Graph exhibits edge
    # (src/knowledge_graph.py) rather than calling diagnose_mechanism()
    # independently — this used to be (and briefly was again, before the
    # graph existed) an inline re-implementation that had already drifted
    # from the shared classifier once (missing the CE-deficit signal),
    # meaning this always-visible card and the deep "Degradation Mechanism
    # Classifier" expander further down could silently disagree on the same
    # cell's verdict. The graph edge is the single source of truth now: the
    # Cell Workbench's Decide & Ask view and the Copilot both read this
    # exact edge for this cell too, so all three surfaces are structurally
    # incapable of disagreeing. get_or_compute_mechanism() falls back to a
    # direct diagnose_mechanism() call when no graph is supplied (e.g. a
    # freshly-uploaded cell not yet part of the platform graph, or a legacy
    # caller/test that doesn't pass graph=).
    _mech = {
        "verdict": "Insufficient data", "verdict_color": "#718096", "verdict_icon": "○",
        "verdict_body": "Not enough degradation signals to classify mechanism. Continue cycling.",
        "confidence_label": "No data", "confidence_color": "#4a5568",
        "confidence_notes": [], "lli_score": 0, "lam_score": 0, "signals": {},
    }
    try:
        if graph is not None:
            from knowledge_graph import get_or_compute_mechanism
            _mech_edge = get_or_compute_mechanism(graph, cell_id, df)
            _mech = {**_mech, **_mech_edge}
        else:
            from recommendations import diagnose_mechanism
            _mech = diagnose_mechanism(df)
    except Exception:
        pass

    # Physics-ML mechanism agreement (Phase 6 physics-informed intelligence):
    # cross-checks _mech's ML verdict above against a physics fit calibrated
    # directly from this cell's own capacity/resistance history (see
    # src/physics_calibration.py) -- reuses recommendations.py's existing
    # caution-note pattern (mechanism_corroboration_note) rather than
    # inventing a new one. None for non-NASA/Severson cells or whenever
    # either side lacks enough data to compare.
    _physics_agreement_note = None
    _agreement = None
    try:
        from physics_calibration import physics_ml_agreement
        from recommendations import physics_ml_agreement_note
        _agreement = physics_ml_agreement(cell_id, df)
        _physics_agreement_note = physics_ml_agreement_note(_agreement)
    except Exception:
        pass

    # ── E1: 12-month SOH trajectory forecast with uncertainty cone ──────────────
    st.markdown("<h4 class='section-header'>12-Month SOH Forecast</h4>", unsafe_allow_html=True)
    import numpy as _np_e1
    _e1_last_cycle = int(df["cycle_number"].iloc[-1])
    _e1_last_soh   = float(df["soh_pct"].iloc[-1])
    _e1_fade_30    = float(latest.get("fade_rate_30cy", 0.0)) * 100   # % per cycle
    _e1_fade_acc   = 0.0
    if "fade_rate_30cy" in df.columns and len(df) >= 60:
        _e1_f1 = float(df["fade_rate_30cy"].iloc[-30:].mean()) * 100
        _e1_f0 = float(df["fade_rate_30cy"].iloc[-60:-30].mean()) * 100
        _e1_fade_acc = max(0.0, _e1_f1 - _e1_f0) / 30  # % SOH / cycle² acceleration
    _e1_cpd = float(st.session_state.get("cycles_per_day", 1.0))
    _CYCLES_12M    = int(365 * _e1_cpd)
    _e1_q10        = float(df["rul_q10"].iloc[-1]) if "rul_q10" in df.columns else None
    _e1_q90        = float(df["rul_q90"].iloc[-1]) if "rul_q90" in df.columns else None
    _e1_eol        = float(st.session_state.get("eol_threshold_pct", 80.0))

    # Reduced C-rate scenario: stress model says C-rate^0.7 factor
    _e1_crate_prof = CELL_STRESS_PROFILES.get(cell_id, {}).get("c_rate", 1.0)
    _e1_reduced    = max(0.1, _e1_crate_prof - 0.5)
    _e1_stress_ratio = (_e1_reduced / _e1_crate_prof) ** 0.7 if _e1_crate_prof > 0.1 else 1.0
    _e1_fade_reduced = _e1_fade_30 * _e1_stress_ratio

    def _e1_proj(fade_base, accel, n_cycles):
        cycles = _np_e1.arange(1, n_cycles + 1)
        soh    = _e1_last_soh - fade_base * cycles - 0.5 * accel * cycles**2
        return (_e1_last_cycle + cycles).tolist(), _np_e1.clip(soh, _e1_eol - 10, 102).tolist()

    _e1_cx,  _e1_cy  = _e1_proj(_e1_fade_30, _e1_fade_acc, _CYCLES_12M)
    _e1_rx,  _e1_ry  = _e1_proj(_e1_fade_reduced, _e1_fade_acc * _e1_stress_ratio, _CYCLES_12M)

    # Uncertainty cone from Q10/Q90 if available, else ±25% fade
    _e1_fade_lo = _e1_fade_30 * 0.75
    _e1_fade_hi = _e1_fade_30 * 1.35 + _e1_fade_acc * _CYCLES_12M * 0.5
    _e1_ux, _e1_uy_lo = _e1_proj(_e1_fade_lo, 0, _CYCLES_12M)
    _e1_ux, _e1_uy_hi = _e1_proj(_e1_fade_hi, _e1_fade_acc, _CYCLES_12M)

    _fig_e1 = go.Figure()
    # Historical SOH
    _e1_hist = df[["cycle_number", "soh_pct"]].tail(100)
    _fig_e1.add_trace(go.Scatter(
        x=_e1_hist["cycle_number"].tolist(), y=_e1_hist["soh_pct"].tolist(),
        name="Actual SOH", line=dict(color="#63b3ed", width=2), mode="lines",
        hovertemplate="Cycle %{x}: %{y:.1f}%<extra>Actual</extra>",
    ))
    # Uncertainty cone (filled band)
    _fig_e1.add_trace(go.Scatter(
        x=_e1_ux + _e1_ux[::-1],
        y=_e1_uy_hi + _e1_uy_lo[::-1],
        fill="toself", fillcolor="rgba(99,179,237,0.10)", line=dict(width=0),
        name="Uncertainty cone", hoverinfo="skip",
    ))
    # Base forecast (current C-rate)
    _fig_e1.add_trace(go.Scatter(
        x=_e1_cx, y=_e1_cy, name=f"Forecast (current {_e1_crate_prof:.1f}C)",
        line=dict(color="#63b3ed", width=2, dash="dash"), mode="lines",
        hovertemplate="Cycle %{x}: %{y:.1f}%<extra>Forecast</extra>",
    ))
    # Reduced C-rate scenario
    _fig_e1.add_trace(go.Scatter(
        x=_e1_rx, y=_e1_ry, name=f"Reduced C-rate ({_e1_reduced:.1f}C)",
        line=dict(color="#48bb78", width=2, dash="dot"), mode="lines",
        hovertemplate="Cycle %{x}: %{y:.1f}%<extra>Reduced C-rate</extra>",
    ))
    _fig_e1.add_hline(y=_e1_eol, line_dash="dot", line_color="#e53e3e", line_width=1,
                      annotation_text=f"EOL ({_e1_eol:.0f}%)", annotation_position="bottom right",
                      annotation_font_color="#e53e3e", annotation_font_size=10)
    _fig_e1.add_vline(x=_e1_last_cycle, line_dash="dot", line_color="#4a5568", line_width=1,
                      annotation_text="Now", annotation_position="top left",
                      annotation_font_color="#4a5568", annotation_font_size=10)
    _fig_e1.update_layout(
        **base_layout(
            height=300, legend=LEGEND_H,
            xaxis=dict(title="Cycle", zeroline=False),
            yaxis=dict(title="SOH %",
                       zeroline=False, range=[max(_e1_eol - 8, 55), 102]),
        ),
    )
    st.plotly_chart(_fig_e1, use_container_width=True)
    # Plain-English summary
    _e1_soh_12m   = max(_e1_eol - 2, _e1_last_soh - _e1_fade_30 * _CYCLES_12M - 0.5 * _e1_fade_acc * _CYCLES_12M**2)
    _e1_soh_12m_r = max(_e1_eol - 2, _e1_last_soh - _e1_fade_reduced * _CYCLES_12M)
    _e1_gain      = _e1_soh_12m_r - _e1_soh_12m
    _e1_txt       = (
        f"At current C-rate ({_e1_crate_prof:.1f}C), projected SOH in 12 months: "
        f"<strong style='color:#63b3ed'>{_e1_soh_12m:.1f}%</strong>. "
        + (f"Reducing to {_e1_reduced:.1f}C could preserve an additional "
           f"<strong style='color:#48bb78'>{_e1_gain:.1f}% SOH</strong> "
           f"({_e1_soh_12m_r:.1f}% projected)." if _e1_gain > 0.1 else "")
        + f" Uncertainty cone: ±25–35% fade variability. ◐ SIMULATED — linear extrapolation."
    )
    _md_html(f"<div style='font-size:12px;color:#a0aec0;padding:4px 0 16px;line-height:1.6'>{_e1_txt}</div>")

    # Always visible to every role (Engineering Usability review finding:
    # this used to only appear once "Engineering details" was checked,
    # which defaults off for every role except Engineer -- meaning Fleet
    # Manager/Executive/Compliance Officer, the roles most needing to trust
    # *why* a decision was made, never saw mechanism reasoning at all. The
    # full signal-by-signal breakdown stays collapsed behind the checkbox
    # below for non-Engineers; only this one-line verdict + confidence is
    # promoted to always-visible.
    _mc_left, _mc_right = st.columns([3, 2])
    with _mc_left:
        render_card(
            f"<span style='font-size:22px'>{_mech['verdict_icon']}</span>"
            f"<div>{metric_tile_html('Degradation Mechanism', _mech['verdict'], value_color=_mech['verdict_color'], value_size='15px')}"
            f"<span style='background:{_mech['confidence_color']}22;border:1px solid {_mech['confidence_color']}55;"
            f"color:{_mech['confidence_color']};font-size:10px;font-weight:700;padding:2px 8px;"
            f"border-radius:8px;display:inline-block;margin-top:4px'>{_mech['confidence_label']} confidence</span>"
            f"</div>",
            padding="14px 20px",
            extra_style="display:flex;align-items:center;gap:12px",
        )
        if _physics_agreement_note:
            st.markdown(
                f"<div style='margin-top:6px;font-size:12px;color:#f6ad55;"
                f"border-top:1px solid #2d374855;padding-top:6px'>⚠ {_physics_agreement_note}</div>",
                unsafe_allow_html=True,
            )

    # ── Section 3: Action (always visible) ──────────────────────────────────
    with _mc_right:
        try:
            from recommendations import classify as _rec_classify
            from consequences import application_fit as _app_fit
            _lat_h  = df.iloc[-1]
            _soh_h  = float(_lat_h["soh_pct"])
            _f30_h  = float(_lat_h.get("fade_rate_30cy", 0.0))
            _f50_h  = float(_lat_h.get("fade_rate_50cy", 0.0))
            _rul_h  = float(_lat_h.get("rul_pred")) if (rul_reliable and _lat_h.get("rul_pred") is not None) else None
            _fit_h  = _app_fit(_soh_h, _f30_h, None)
            _rec_h  = _rec_classify(_soh_h, _f30_h, _f50_h, rul_reliable, _rul_h, _fit_h)
            _al_h, _ac_h, _abg_h = ACTION_META[_rec_h["action"]]
            _cc_h, _cl_h = CONF_META[_rec_h["confidence"]]
            _md_html(
                f"<div style='background:{_abg_h};border:2px solid {_ac_h}55;border-radius:10px;"
                f"padding:14px 20px'>"
                f"<div style='font-size:10px;font-weight:700;color:{_ac_h}99;"
                f"text-transform:uppercase;letter-spacing:0.1em;margin-bottom:4px'>Recommended Action</div>"
                f"<div style='font-size:18px;font-weight:800;color:{_ac_h}'>{_al_h}</div>"
                f"<div style='margin-top:6px'>"
                f"<span style='background:{_cc_h}22;border:1px solid {_cc_h}55;color:{_cc_h};"
                f"font-size:10px;font-weight:700;padding:2px 8px;border-radius:8px'>{_cl_h}</span>"
                f"</div></div>"
            )
            if st.button("Full decision analysis →", key=f"h_to_dec_{cell_id}", use_container_width=True):
                st.session_state.page = "decision"
                st.rerun()
        except Exception:
            pass

    # ── Engineering Details toggle ───────────────────────────────────────────
    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
    _default_eng = st.session_state.get("user_role", "Engineer") == "Engineer"
    _show_eng = st.checkbox(
        "Engineering details",
        key=f"health_eng_{cell_id}",
        value=_default_eng,
        help="Fade rate analysis, dQ/dV, resistance model, PyBaMM projection, and all diagnostic expanders.",
    )
    if not _show_eng:
        return

    render_engineering_diagnostics(
        df, _rdf, cell_id, bundle, rul_reliable,
        knee, _mech, _agreement, _physics_agreement_note,
    )
