"""Page: Health"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import numpy as np

from utils import (
    base_layout, LEGEND_H, PLOTLY_CONFIG, _md_html, soh_status,
    _cell_provenance, _analysis_provenance, NASA_CELL_IDS,
)
from design_system import provenance_banner
from knee_detection import detect_knee, degradation_phases


def page_health(df: pd.DataFrame, split_cycle: int, cell_id: str):
    st.markdown("# Health")

    _cp = _cell_provenance(cell_id)
    _prov_detail = {
        "measured": (
            f"Capacity and resistance data for <strong>{cell_id}</strong> are real measurements "
            f"from the NASA PCoE Battery Aging Dataset (Saha &amp; Goebel, 2007). "
            f"Derived analyses (EIS, dQ/dV, rate capability) use physics models applied to "
            f"these measurements and are labelled ◐ SIMULATED individually."
        ),
        "synthetic": (
            f"<strong>{cell_id}</strong> is a physics-informed synthetic cell generated by "
            f"<code>generate_cell_data()</code> — no physical measurements underlie any value "
            f"on this page. All analyses are labelled ○ SYNTHETIC. "
            f"<strong>Do not use synthetic cell outputs for real engineering decisions.</strong>"
        ),
    }[_cp]
    _md_html(provenance_banner(_cp, _prov_detail))

    latest = df.iloc[-1]
    current_soh = latest["soh_pct"]
    status_label, status_colour = soh_status(current_soh)

    knee = detect_knee(df["soh_pct"], df["cycle_number"])
    sop_pct = float(latest["sop_pct"]) if "sop_pct" in latest.index else None

    knee_note = ""
    if knee["detected"]:
        k_cy  = knee["cycle"]
        k_soh = knee["soh_at_knee"]
        cur   = int(latest["cycle_number"])
        if cur >= k_cy:
            knee_note = f"· ⚡ Knee at cycle {k_cy} ({k_soh:.1f}% SOH) — now in accelerating phase"
        else:
            knee_note = f"· Knee projected ~cycle {k_cy} ({k_soh:.1f}% SOH)"

    _md_html(
        f"""
        <div class="hero-card">
            <div class="hero-label">Health Assessment · {cell_id}</div>
            <div class="hero-value {status_colour}">{current_soh:.1f}% SOH</div>
            <div class="hero-sub">
                Fading at ~{latest['fade_rate_50cy']*1000:.2f} mAh/cycle (50-cycle avg)
                &nbsp;·&nbsp; Internal resistance: {latest.get('resistance_ohm',0):.3f} Ω
                &nbsp;·&nbsp; Peak power: {f"{sop_pct:.0f}% of initial" if sop_pct else "—"}
                {knee_note}
            </div>
        </div>
        """
    )

    col1, col2 = st.columns(2)

    cap_anomalies = df[df.get("capacity_anomaly", pd.Series(False, index=df.index))] if "capacity_anomaly" in df.columns else df.iloc[0:0]
    res_anomalies = df[df.get("resistance_anomaly", pd.Series(False, index=df.index))] if "resistance_anomaly" in df.columns else df.iloc[0:0]

    with col1:
        st.markdown("<div class='section-header'>Capacity Fade</div>", unsafe_allow_html=True)
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=df["cycle_number"], y=df["capacity_fade_ah"] * 1000,
            fill="tozeroy", fillcolor="rgba(252,129,129,0.08)",
            line=dict(color="#fc8181", width=2),
            hovertemplate="Cycle %{x}: %{y:.1f} mAh lost<extra></extra>",
            showlegend=False,
        ))
        if len(cap_anomalies) > 0:
            fig.add_trace(go.Scatter(
                x=cap_anomalies["cycle_number"],
                y=cap_anomalies["capacity_fade_ah"] * 1000,
                mode="markers", name=f"Anomaly ({len(cap_anomalies)})",
                marker=dict(color="#f6ad55", size=7, symbol="diamond",
                            line=dict(color="#1a202c", width=1)),
                hovertemplate="Cycle %{x}: anomalous capacity<extra>⚠ Anomaly</extra>",
            ))
        if knee["detected"]:
            fig.add_vline(x=knee["cycle"], line=dict(color="#9f7aea", width=1.5, dash="dot"),
                          annotation_text=f"Knee ({knee['cycle']})",
                          annotation=dict(font=dict(size=9, color="#9f7aea")))
        fig.update_layout(
            height=280,
            **base_layout(
                legend=LEGEND_H,
                xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                yaxis=dict(title="mAh lost", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
            ),
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.markdown("<div class='section-header'>Internal Resistance</div>", unsafe_allow_html=True)
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(
            x=df["cycle_number"], y=df["resistance_ohm"] * 1000,
            line=dict(color="#4a5568", width=1), name="Raw",
            hovertemplate="Cycle %{x}: %{y:.1f} mΩ<extra></extra>",
        ))
        fig2.add_trace(go.Scatter(
            x=df["cycle_number"],
            y=df["resistance_ohm"].rolling(30, min_periods=1).mean() * 1000,
            name="30-cycle avg", line=dict(color="#f6ad55", width=2),
            hovertemplate="Cycle %{x}: %{y:.1f} mΩ<extra>30-cy avg</extra>",
        ))
        if len(res_anomalies) > 0:
            fig2.add_trace(go.Scatter(
                x=res_anomalies["cycle_number"],
                y=res_anomalies["resistance_ohm"] * 1000,
                mode="markers", name=f"Spike ({len(res_anomalies)})",
                marker=dict(color="#fc8181", size=7, symbol="diamond",
                            line=dict(color="#1a202c", width=1)),
                hovertemplate="Cycle %{x}: resistance spike<extra>⚠ Spike</extra>",
            ))
        fig2.update_layout(
            **base_layout(
                height=280, legend=LEGEND_H,
                xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                yaxis=dict(title="mΩ", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
            ),
        )
        st.plotly_chart(fig2, use_container_width=True)

    INFLECTION_MIN_CYCLE = 30
    ACCEL_FACTOR         = 2.0
    first_accel: int | None = None

    if "fade_rate_30cy" in df.columns:
        df_baseline = df[df["cycle_number"] <= INFLECTION_MIN_CYCLE]
        df_post30   = df[df["cycle_number"] >  INFLECTION_MIN_CYCLE]
        if len(df_baseline) > 0:
            baseline_rate = df_baseline["fade_rate_30cy"].mean()
            if baseline_rate > 0 and not pd.isna(baseline_rate):
                accel_threshold = baseline_rate * ACCEL_FACTOR
                accel_rows = df_post30[df_post30["fade_rate_30cy"] > accel_threshold]
                if len(accel_rows) > 0:
                    first_accel = int(accel_rows["cycle_number"].iloc[0])

    st.markdown(
        "<div class='section-header'>Fade Rate — Is degradation accelerating?</div>",
        unsafe_allow_html=True,
    )
    fig3 = go.Figure()
    fig3.add_trace(go.Scatter(
        x=df["cycle_number"], y=df["fade_rate_10cy"] * 1000,
        line=dict(color="#4a5568", width=1), name="10-cycle window",
    ))
    fig3.add_trace(go.Scatter(
        x=df["cycle_number"], y=df["fade_rate_30cy"] * 1000,
        line=dict(color="#63b3ed", width=2), name="30-cycle window",
    ))
    fig3.add_trace(go.Scatter(
        x=df["cycle_number"], y=df["fade_rate_50cy"] * 1000,
        line=dict(color="#48bb78", width=2), name="50-cycle window",
    ))
    if first_accel is not None:
        fig3.add_vline(
            x=first_accel,
            line=dict(color="#fc8181", width=1.5, dash="dash"),
            annotation_text=f"Fade acceleration threshold: {ACCEL_FACTOR:.0f}× {INFLECTION_MIN_CYCLE}-cycle baseline (heuristic)",
            annotation_position="top right",
            annotation=dict(font=dict(size=10, color="#fc8181"), bgcolor="rgba(26,32,44,0.85)"),
        )
    if knee["detected"]:
        fig3.add_vline(
            x=knee["cycle"],
            line=dict(color="#9f7aea", width=1.5, dash="dot"),
            annotation_text=f"Knee-point ({knee['cycle']})",
            annotation_position="top left",
            annotation=dict(font=dict(size=10, color="#9f7aea"), bgcolor="rgba(26,32,44,0.85)"),
        )
    fig3.update_layout(
        **base_layout(
            height=280, legend=LEGEND_H,
            xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
            yaxis=dict(title="mAh lost per cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
        ),
    )
    st.plotly_chart(fig3, use_container_width=True)

    if first_accel is not None:
        st.markdown(
            f"<div style='background:rgba(252,129,129,0.08);border:1px solid rgba(252,129,129,0.3);"
            f"border-radius:8px;padding:12px 16px;font-size:12px;color:#fed7d7;margin-top:-8px'>"
            f"⚠ <strong>Fade acceleration detected at cycle {first_accel}</strong> — "
            f"30-cycle rolling rate exceeded {ACCEL_FACTOR:.0f}× the cycle-1–{INFLECTION_MIN_CYCLE} baseline. "
            f"Schedule inspection or monitor closely."
            f"</div>",
            unsafe_allow_html=True,
        )

    early = df[df["confidence_tag"] == "Calibrating"]
    if len(early) > 0:
        st.info(
            f"**Calibrating** — the first {len(early)} cycles show higher variability "
            f"while rolling-window features stabilise. Readings from cycle 50 onward are reliable."
        )

    n_cap_anom = len(cap_anomalies)
    n_res_anom = len(res_anomalies)
    if n_cap_anom > 0 or n_res_anom > 0:
        st.markdown(
            f"<div style='background:rgba(246,173,85,0.08);border:1px solid rgba(246,173,85,0.3);"
            f"border-radius:8px;padding:12px 16px;font-size:12px;color:#fefcbf;margin-top:8px'>"
            f"⚠ <strong>Anomalous cycles detected</strong> — "
            f"{n_cap_anom} capacity outlier(s) · {n_res_anom} resistance spike(s) "
            f"(>2.5σ from 30-cycle rolling baseline). "
            f"Isolated anomalies are often measurement noise. Clustered anomalies may indicate "
            f"lithium plating, electrolyte leakage, or tab resistance changes."
            f"</div>",
            unsafe_allow_html=True,
        )

    st.markdown("<div class='section-header'>Degradation Phase Analysis</div>", unsafe_allow_html=True)
    phase_labels = degradation_phases(df["soh_pct"], df["cycle_number"])
    phase_counts = phase_labels.value_counts()
    n_early = int(phase_counts.get("Early", 0))
    n_plateau = int(phase_counts.get("Plateau", 0))
    n_accel = int(phase_counts.get("Accelerating", 0))
    current_phase = knee["phase"]
    PHASE_COLOUR = {"Early": "#63b3ed", "Plateau": "#48bb78", "Accelerating": "#fc8181", "Unknown": "#4a5568"}
    pc = PHASE_COLOUR.get(current_phase, "#4a5568")

    _md_html(
        f"""
        <div style="background:#1e2a38;border:1px solid #2d3748;border-radius:10px;padding:18px 22px;margin-bottom:16px">
            <div style="display:flex;gap:32px;flex-wrap:wrap;align-items:flex-start">
                <div>
                    <div style="font-size:11px;color:#4a5568;text-transform:uppercase;letter-spacing:0.07em">Current phase</div>
                    <div style="font-size:26px;font-weight:700;color:{pc}">{current_phase}</div>
                    <div style="font-size:11px;color:#4a5568;margin-top:2px">
                        {"Knee at cycle " + str(knee["cycle"]) + f" ({knee['soh_at_knee']}% SOH)" if knee["detected"] else "No knee detected yet"}
                    </div>
                </div>
                <div style="border-left:1px solid #2d3748;padding-left:24px">
                    <div style="font-size:11px;color:#4a5568;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.07em">Cycle breakdown</div>
                    <div style="font-size:12px;color:#a0aec0;line-height:2">
                        <span style="color:#63b3ed">Early</span> — {n_early} cycles (rolling features stabilising)<br>
                        <span style="color:#48bb78">Plateau</span> — {n_plateau} cycles (linear degradation regime)<br>
                        <span style="color:#fc8181">Accelerating</span> — {n_accel} cycles (post-knee, rapid fade)
                    </div>
                </div>
                <div style="border-left:1px solid #2d3748;padding-left:24px;max-width:280px">
                    <div style="font-size:11px;color:#4a5568;margin-bottom:6px;text-transform:uppercase;letter-spacing:0.07em">What this means</div>
                    <div style="font-size:11px;color:#718096;line-height:1.7">
                        {"The cell is past its knee point — degradation has entered the rapid-fade regime. "
                         "Remaining life estimates are shorter and less predictable than in the plateau phase. "
                         "Prioritise replacement planning."
                         if current_phase == "Accelerating" else
                         "The cell is in the stable plateau phase — degradation is approximately linear "
                         "and predictable. RUL estimates are most reliable here."
                         if current_phase == "Plateau" else
                         "Early cycles — rolling-window features are still stabilising. "
                         "Fade rate estimates will become reliable from cycle 50 onward."}
                    </div>
                </div>
            </div>
        </div>
        """
    )

    _dqdv_prov = _analysis_provenance(cell_id, "derived")
    _dqdv_badge = {"measured": "◐ SIMULATED", "simulated": "◐ SIMULATED", "synthetic": "○ SYNTHETIC"}[_dqdv_prov]
    with st.expander(f"🔬 dQ/dV Degradation Analysis — {_dqdv_badge}", expanded=False):
        try:
            from dqdv import simulate_vq_curve
            _prov_dqdv = _analysis_provenance(cell_id, "derived")
            _md_html(provenance_banner(_prov_dqdv,
                "V(Q) and dQ/dV curves are computed by <code>simulate_vq_curve()</code> — a physics "
                "model parameterised from the cell's measured capacity and resistance. "
                "No voltage traces were logged during cycling; these are not oscilloscope measurements."
            ))

            n_cycles = len(df)
            pct_indices = [int(n_cycles * p) for p in [0.05, 0.25, 0.50, 0.75, 0.95]]
            pct_indices = [min(max(i, 0), n_cycles - 1) for i in pct_indices]
            rep_rows = [df.iloc[i] for i in pct_indices]

            _COLORS = ["#63b3ed", "#7fbfea", "#f6ad55", "#ed8936", "#fc8181"]
            fig_vq = go.Figure()
            for i, (row, color) in enumerate(zip(rep_rows, _COLORS)):
                try:
                    cap = float(row["capacity_ah"])
                    res = float(row.get("resistance_ohm", 0.02))
                    Q, V = simulate_vq_curve(cap, res)
                    fig_vq.add_trace(go.Scatter(
                        x=Q.tolist(), y=V.tolist(),
                        mode="lines",
                        name=f"Cycle {int(row['cycle_number'])}",
                        line=dict(color=color, width=1.8),
                        hovertemplate="Q=%{x:.3f} Ah  V=%{y:.3f} V<extra>Cycle " + str(int(row["cycle_number"])) + "</extra>",
                    ))
                except Exception:
                    pass
            fig_vq.update_layout(
                **base_layout(
                    height=300, legend=LEGEND_H,
                    xaxis=dict(title="Discharge Capacity (Ah)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    yaxis=dict(title="Voltage (V)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                ),
            )
            fig_vq.update_layout(title=dict(text="Simulated Discharge Voltage Curves (V vs Q)", font=dict(size=12, color="#a0aec0"), x=0))
            st.plotly_chart(fig_vq, use_container_width=True)

            dqdv_cols = ["dqdv_peak_soc", "dqdv_peak_value"]
            if all(c in df.columns for c in dqdv_cols):
                fig_peak = go.Figure()
                fig_peak.add_trace(go.Scatter(
                    x=df["cycle_number"], y=df["dqdv_peak_soc"],
                    name="Peak SOC Position", line=dict(color="#63b3ed", width=2),
                    hovertemplate="Cycle %{x}: %{y:.3f}<extra>Peak SOC</extra>",
                ))
                fig_peak.add_trace(go.Scatter(
                    x=df["cycle_number"], y=df["dqdv_peak_value"],
                    name="Peak Amplitude (Ah/V)", line=dict(color="#f6ad55", width=2),
                    yaxis="y2",
                    hovertemplate="Cycle %{x}: %{y:.2f} Ah/V<extra>Peak Amplitude</extra>",
                ))
                fig_peak.update_layout(
                    **base_layout(
                        height=300, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Peak SOC Position", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False, color="#63b3ed"),
                        yaxis2=dict(title="Peak Amplitude (Ah/V)", overlaying="y", side="right",
                                    gridcolor="#232d3b", linecolor="#2d3748", zeroline=False, color="#f6ad55"),
                    ),
                )
                fig_peak.update_layout(title=dict(text="dQ/dV Peak Shift Over Aging", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(fig_peak, use_container_width=True)
                st.caption("Peak SOC shifts left and amplitude drops as active material is lost — a direct electrochemical signature of degradation.")

            if "dqdv_fwhm" in df.columns:
                fig_fwhm = go.Figure()
                fig_fwhm.add_trace(go.Scatter(
                    x=df["cycle_number"], y=df["dqdv_fwhm"],
                    line=dict(color="#48bb78", width=2),
                    hovertemplate="Cycle %{x}: %{y:.4f} Ah<extra>FWHM</extra>",
                    showlegend=False,
                ))
                fig_fwhm.update_layout(
                    **base_layout(
                        height=260, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="FWHM (Ah)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                fig_fwhm.update_layout(title=dict(text="dQ/dV Peak Width (FWHM) — Broadening = increased heterogeneity", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(fig_fwhm, use_container_width=True)

            st.markdown("<div class='section-header'>⚗️ Degradation Mechanism Interpretation</div>", unsafe_allow_html=True)
            if all(c in df.columns for c in ["dqdv_peak_soc", "dqdv_peak_value", "dqdv_fwhm"]):
                import numpy as _np2
                early_mech = df[df.cycle_number <= df.cycle_number.quantile(0.10)]
                late_mech  = df[df.cycle_number >= df.cycle_number.quantile(0.90)]
                if len(early_mech) > 0 and len(late_mech) > 0 and early_mech.dqdv_peak_value.mean() > 1e-9 and early_mech.dqdv_fwhm.mean() > 1e-9:
                    peak_soc_shift  = early_mech.dqdv_peak_soc.mean() - late_mech.dqdv_peak_soc.mean()
                    amplitude_drop  = (early_mech.dqdv_peak_value.mean() - late_mech.dqdv_peak_value.mean()) / early_mech.dqdv_peak_value.mean() * 100
                    fwhm_change     = (late_mech.dqdv_fwhm.mean() - early_mech.dqdv_fwhm.mean()) / early_mech.dqdv_fwhm.mean() * 100
                    if peak_soc_shift > 0.05 and amplitude_drop > 10:
                        dominant = "LLI + LAM (mixed)"
                    elif peak_soc_shift > 0.05:
                        dominant = "LLI (Loss of Lithium Inventory)"
                    elif amplitude_drop > 15:
                        dominant = "LAM (Loss of Active Material)"
                    elif fwhm_change > 20:
                        dominant = "LAM_NE (Graphite heterogeneity)"
                    else:
                        dominant = "Early stage / inconclusive"
                    _mech_explanations = {
                        "LLI (Loss of Lithium Inventory)": "SEI layer growth is consuming cyclable lithium. Common in calendar aging and elevated temperature operation. Characteristic: peak shifts to lower SOC values.",
                        "LAM (Loss of Active Material)": "Electrode active sites are being lost, reducing overall capacity. Common with high C-rate cycling. Characteristic: peak amplitude decreases proportionally to capacity loss.",
                        "LLI + LAM (mixed)": "Both mechanisms active simultaneously. Typical of aged cells with combined calendar and cycle stress.",
                        "LAM_NE (Graphite heterogeneity)": "Graphite particle cracking or lithium plating creating heterogeneous intercalation sites. Characteristic: peak broadening without large position shift.",
                        "Early stage / inconclusive": "Insufficient degradation to identify dominant mechanism. Continue monitoring — revisit after further cycling.",
                    }
                    explanation = _mech_explanations.get(dominant, "")
                    m1, m2, m3 = st.columns(3)
                    with m1:
                        st.metric("Peak SOC Shift", f"{peak_soc_shift:+.3f}", "← left = LLI signature")
                    with m2:
                        st.metric("Amplitude Drop", f"{amplitude_drop:.1f}%", "↓ drop = LAM signature")
                    with m3:
                        st.metric("FWHM Change", f"{fwhm_change:+.1f}%", "↑ broaden = heterogeneity")
                    st.info(f"**Dominant mechanism: {dominant}**\n\n{explanation}")
                else:
                    st.info("Insufficient dQ/dV data to classify degradation mechanism.")
            else:
                st.info("dQ/dV columns unavailable for mechanism interpretation.")
        except Exception as _e:
            st.info(f"dQ/dV analysis unavailable: {_e}")

    if "coulombic_efficiency" in df.columns:
        _ce_prov = _analysis_provenance(cell_id, "cycle")
        _ce_badge = "● MEASURED" if _ce_prov == "measured" else "○ SYNTHETIC"
        with st.expander(f"⚡ Coulombic Efficiency (CE) Analysis — {_ce_badge}", expanded=False):
            try:
                ce_latest  = float(df["coulombic_efficiency"].iloc[-1])
                ce_initial = float(df["coulombic_efficiency"].iloc[:10].mean())
                ce_drop    = ce_initial - ce_latest

                _ce1, _ce2, _ce3 = st.columns(3)
                with _ce1:
                    st.metric("Current CE", f"{ce_latest*100:.3f}%",
                              help="Q_discharge / Q_charge — lithium consumed by SEI each cycle")
                with _ce2:
                    st.metric("CE Drop from Cycle 1", f"{ce_drop*100:.3f}%",
                              delta=f"{-ce_drop*100:.3f}%",
                              help="Cumulative lithium inventory loss signature")
                with _ce3:
                    ce_risk = "High" if ce_latest < 0.993 else ("Moderate" if ce_latest < 0.997 else "Low")
                    st.metric("Lithium Loss Risk", ce_risk,
                              help="< 99.7%: moderate SEI growth; < 99.3%: accelerated LLI")

                _md_html("""<div style="font-size:12px;color:#718096;margin:8px 0 12px;line-height:1.6"><strong style="color:#a0aec0">Why CE matters:</strong> Every cycle where CE &lt; 100% permanently loses cyclable lithium to the SEI layer. A CE drop from 99.95% → 99.30% may seem small but represents ~0.65% lithium lost per cycle — the dominant degradation mechanism in calendar-aged cells. CATL and BYD track cumulative CE deficit as the primary warranty signal for LLI-dominated failures.</div>""")

                fig_ce = go.Figure()
                fig_ce.add_trace(go.Scatter(
                    x=df["cycle_number"].tolist(),
                    y=(df["coulombic_efficiency"] * 100).tolist(),
                    name="CE per cycle", mode="lines",
                    line=dict(color="#4a5568", width=1),
                    hovertemplate="Cycle %{x}: %{y:.4f}%<extra>CE</extra>",
                ))
                if "ce_rolling_30cy" in df.columns:
                    fig_ce.add_trace(go.Scatter(
                        x=df["cycle_number"].tolist(),
                        y=(df["ce_rolling_30cy"] * 100).tolist(),
                        name="30-cycle rolling avg", mode="lines",
                        line=dict(color="#63b3ed", width=2),
                        hovertemplate="Cycle %{x}: %{y:.4f}%<extra>30cy avg</extra>",
                    ))
                fig_ce.add_hline(y=99.70, line=dict(color="#f6ad55", width=1, dash="dot"),
                                 annotation_text="99.70% — moderate risk threshold",
                                 annotation=dict(font=dict(size=9, color="#f6ad55")))
                fig_ce.add_hline(y=99.30, line=dict(color="#fc8181", width=1, dash="dot"),
                                 annotation_text="99.30% — high LLI risk",
                                 annotation=dict(font=dict(size=9, color="#fc8181")))
                fig_ce.update_layout(
                    **base_layout(
                        height=280, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Coulombic Efficiency (%)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                fig_ce.update_layout(title=dict(text="Coulombic Efficiency — Q_discharge / Q_charge", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(fig_ce, use_container_width=True)

                ce_deficit = (1.0 - df["coulombic_efficiency"]).cumsum()
                fig_lii = go.Figure()
                fig_lii.add_trace(go.Scatter(
                    x=df["cycle_number"].tolist(),
                    y=(ce_deficit * float(df["capacity_ah"].iloc[0]) * 1000).tolist(),
                    fill="tozeroy", fillcolor="rgba(252,129,129,0.08)",
                    line=dict(color="#fc8181", width=2),
                    hovertemplate="Cycle %{x}: %{y:.2f} mAh cumulative LLI<extra></extra>",
                    showlegend=False,
                ))
                fig_lii.update_layout(
                    **base_layout(
                        height=220, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Cumulative Li loss (mAh)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                fig_lii.update_layout(title=dict(text="Cumulative Lithium Inventory Loss (LLI) from CE Deficit", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(fig_lii, use_container_width=True)
            except Exception as _ce_e:
                st.info(f"CE analysis unavailable: {_ce_e}")

    if "cumulative_kwh" in df.columns:
        _thru_badge = "● MEASURED" if cell_id in NASA_CELL_IDS else "○ SYNTHETIC"
        with st.expander(f"📈 Energy & Capacity Throughput — {_thru_badge}", expanded=False):
            try:
                total_kwh = float(df["cumulative_kwh"].iloc[-1])
                total_ah  = float(df["cumulative_ah"].iloc[-1])
                eq_cy     = float(df["equivalent_cycles"].iloc[-1]) if "equivalent_cycles" in df.columns and not pd.isna(df["equivalent_cycles"].iloc[-1]) else None

                _t1, _t2, _t3 = st.columns(3)
                with _t1:
                    st.metric("Total Energy Delivered", f"{total_kwh:.2f} kWh",
                              help="Cumulative energy throughput — BYD/CATL warranty metric")
                with _t2:
                    st.metric("Total Capacity Delivered", f"{total_ah:.0f} Ah",
                              help="Cumulative Ah throughput across all cycles")
                with _t3:
                    if eq_cy is not None:
                        raw_cy = int(df["cycle_number"].iloc[-1])
                        st.metric("Equivalent Cycles", f"{eq_cy:,.0f}",
                                  delta=f"{eq_cy - raw_cy:+,.0f} vs raw",
                                  help="Stress-normalized cycle count: raw cycles × stress factor")
                    else:
                        st.metric("Equivalent Cycles", "—", help="Not available for this data source")

                fig_kwh = go.Figure()
                fig_kwh.add_trace(go.Scatter(
                    x=df["cycle_number"].tolist(),
                    y=df["cumulative_kwh"].tolist(),
                    fill="tozeroy", fillcolor="rgba(99,179,237,0.07)",
                    line=dict(color="#63b3ed", width=2),
                    hovertemplate="Cycle %{x}: %{y:.3f} kWh delivered<extra></extra>",
                    showlegend=False,
                ))
                fig_kwh.update_layout(
                    **base_layout(
                        height=250, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Cumulative kWh", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                fig_kwh.update_layout(title=dict(text="Cumulative Energy Throughput (kWh) — Warranty Accounting Metric", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(fig_kwh, use_container_width=True)
            except Exception as _te:
                st.info(f"Throughput analysis unavailable: {_te}")

    _eis_badge = "◐ SIMULATED" if cell_id in NASA_CELL_IDS else "○ SYNTHETIC"
    with st.expander(f"🔬 EIS Impedance Analysis — {_eis_badge}", expanded=False):
        try:
            import numpy as _np_eis
            _md_html(provenance_banner(
                "simulated" if cell_id in NASA_CELL_IDS else "synthetic",
                "Impedance components (R_ohm, R_SEI, R_ct, σ_w) are derived from DC resistance via "
                "fixed physics-attribution fractions, <strong>not from frequency-domain impedance "
                "spectroscopy measurements</strong>. The Nyquist plot is computed from a Randles "
                "circuit model parameterised by these attributed values. "
                "Connect a real EIS instrument file (Gamry / BioLogic .DTA/.mpt) to replace this "
                "with measured impedance data."
            ))
            _eis_cols = ["r_ohm_eis", "r_sei", "r_ct", "sigma_w"]
            _has_eis  = all(c in df.columns for c in _eis_cols)
            if not _has_eis:
                st.info("EIS columns not available in this dataset. Regenerate data to enable.")
            else:
                st.caption(
                    "Randles-circuit decomposition of the measured DC resistance. "
                    "R_ohm (bulk electrolyte, constant), R_SEI (SEI layer, grows with √time), "
                    "R_ct (charge transfer, grows with cycle^0.6), σ_w (Warburg / diffusion coefficient)."
                )
                _n = len(df)
                _snap_idx = [max(0, int(_n * f) - 1) for f in [0.05, 0.50, 0.95]]
                _snap_labels = ["Early (5%)", "Mid (50%)", "Late (95%)"]

                _FREQ = _np_eis.logspace(5, -2, 60)
                _OMEGA = 2 * _np_eis.pi * _FREQ
                _nyq_colors = ["#48bb78", "#63b3ed", "#fc8181"]
                _fig_nyq = go.Figure()
                for _si, (_idx, _lbl, _col) in enumerate(zip(_snap_idx, _snap_labels, _nyq_colors)):
                    _row = df.iloc[_idx]
                    _r_ohm = float(_row["r_ohm_eis"])
                    _r_sei = float(_row["r_sei"])
                    _r_ct  = float(_row["r_ct"])
                    _sw    = float(_row["sigma_w"])
                    _alpha_sei, _alpha_dl = 0.82, 0.88
                    _Q_sei, _Q_dl = 8e-6, 3e-5
                    _Z_sei_cpe = 1.0 / (_Q_sei * (1j * _OMEGA) ** _alpha_sei)
                    _Z_dl_cpe  = 1.0 / (_Q_dl  * (1j * _OMEGA) ** _alpha_dl)
                    _Z_sei = (_r_sei * _Z_sei_cpe) / (_r_sei + _Z_sei_cpe)
                    _Z_w   = _sw * (1 - 1j) / _np_eis.sqrt(_np_eis.maximum(_OMEGA, 1e-9))
                    _Z_ct  = (_r_ct * (_Z_dl_cpe + _Z_w)) / (_r_ct + _Z_dl_cpe + _Z_w)
                    _Z     = _r_ohm + _Z_sei + _Z_ct
                    _fig_nyq.add_trace(go.Scatter(
                        x=_Z.real.tolist(), y=(-_Z.imag).tolist(),
                        mode="lines", name=_lbl,
                        line=dict(color=_col, width=2),
                        hovertemplate=f"<b>{_lbl}</b><br>Z' = %{{x:.4f}} Ω<br>-Z'' = %{{y:.4f}} Ω<extra></extra>",
                    ))
                _fig_nyq.update_layout(
                    **base_layout(
                        height=300, legend=LEGEND_H,
                        xaxis=dict(title="Z' (Ω) — Real", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="-Z'' (Ω) — Imaginary", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                _fig_nyq.update_layout(title=dict(text="Nyquist Plot at 3 Lifecycle Stages (CPE Modified Randles)", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(_fig_nyq, use_container_width=True, config={**PLOTLY_CONFIG, "toImageButtonOptions": {**PLOTLY_CONFIG["toImageButtonOptions"], "filename": "nyquist_plot"}})

                _fig_eis_trend = go.Figure()
                for _col_name, _label, _color in [
                    ("r_sei", "R_SEI (SEI layer)", "#f6ad55"),
                    ("r_ct",  "R_ct (charge transfer)", "#63b3ed"),
                    ("r_ohm_eis", "R_ohm (electrolyte)", "#48bb78"),
                ]:
                    _fig_eis_trend.add_trace(go.Scatter(
                        x=df["cycle_number"].tolist(), y=df[_col_name].tolist(),
                        mode="lines", name=_label,
                        line=dict(width=2),
                        hovertemplate=f"Cycle %{{x}}: %{{y:.4f}} Ω ({_label})<extra></extra>",
                    ))
                _fig_eis_trend.update_layout(
                    **base_layout(
                        height=270, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Resistance (Ω)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                _fig_eis_trend.update_layout(title=dict(text="EIS Component Trends — Mechanism Attribution", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(_fig_eis_trend, use_container_width=True, config={**PLOTLY_CONFIG, "toImageButtonOptions": {**PLOTLY_CONFIG["toImageButtonOptions"], "filename": "eis_component_trends"}})

                _late = df.iloc[-1]
                _r0   = df.iloc[0]["r_sei"]
                _sei_growth = (_late["r_sei"] - _r0) / max(_r0, 1e-9) * 100
                _ct_growth  = (_late["r_ct"]  - df.iloc[0]["r_ct"]) / max(df.iloc[0]["r_ct"], 1e-9) * 100
                if _sei_growth > _ct_growth * 1.3:
                    _mech = "Calendar / SEI-dominated"
                    _mech_color = "#f6ad55"
                    _mech_explain = "R_SEI growth outpaces R_ct — primary degradation is SEI thickening from calendar storage and temperature exposure."
                elif _ct_growth > _sei_growth * 1.3:
                    _mech = "Cycle / Charge-transfer-dominated"
                    _mech_color = "#63b3ed"
                    _mech_explain = "R_ct growth outpaces R_SEI — primary degradation is charge-transfer impedance from active-material loss and lithium plating."
                else:
                    _mech = "Mixed SEI + charge-transfer"
                    _mech_color = "#48bb78"
                    _mech_explain = "Balanced SEI and charge-transfer growth — both calendar and cycling contribute comparably."
                _md_html(f"""<div style="background:rgba(26,32,44,0.7);border:1px solid #2d3748;border-radius:8px;padding:12px 16px;font-size:13px"><span style="color:{_mech_color};font-weight:700">{_mech}</span><span style="color:#a0aec0;margin-left:10px">{_mech_explain}</span><br><span style="color:#718096;font-size:12px;margin-top:4px;display:block">R_SEI growth: {_sei_growth:.1f}% · R_ct growth: {_ct_growth:.1f}%</span></div>""")
        except Exception as _eis_e:
            st.info(f"EIS analysis unavailable: {_eis_e}")

    _form_badge = "◐ SIMULATED" if cell_id in NASA_CELL_IDS else "○ SYNTHETIC"
    with st.expander(f"🧪 Formation Protocol Analysis — {_form_badge}", expanded=False):
        try:
            import numpy as _np_form
            _md_html(provenance_banner(
                "simulated" if cell_id in NASA_CELL_IDS else "synthetic",
                "Formation metrics (ICL, CE stabilisation) are read from the first cycles of "
                "this cell's cycle-summary data. For synthetic cells this data was generated, "
                "not measured. For NASA cells it is measured cycle capacity — "
                "but NASA cells were cycled at fixed conditions after formation, not logged during "
                "formation itself. CE values for NASA cells are <strong>not directly measured</strong>; "
                "they are model outputs from <code>generate_cell_data()</code> logic."
            ))
            _form_cycles = df[df["cycle_number"] <= 10].copy() if len(df) >= 10 else df.copy()
            if len(_form_cycles) < 3:
                st.info("Need at least 3 cycles to analyse formation.")
            else:
                st.caption(
                    "Formation = first 3–10 cycles. SEI forms on the anode, consuming cyclable lithium "
                    "(Irreversible Capacity Loss, ICL). CE rises steeply from ~90–95% toward >99.9% as the "
                    "SEI stabilises. Rate and magnitude predict long-term calendar ageing."
                )
                _q0   = float(_form_cycles["capacity_ah"].iloc[0])
                _q3   = float(_form_cycles["capacity_ah"].iloc[min(2, len(_form_cycles)-1)])
                _icl  = (_q0 - _q3) / max(_q0, 1e-9) * 100
                _ce0  = float(_form_cycles["coulombic_efficiency"].iloc[0]) * 100 if "coulombic_efficiency" in _form_cycles.columns else None
                _ce3  = float(_form_cycles["coulombic_efficiency"].iloc[min(2, len(_form_cycles)-1)]) * 100 if "coulombic_efficiency" in _form_cycles.columns else None

                _fc1, _fc2, _fc3 = st.columns(3)
                _fc1.metric("ICL (Cycles 1→3)", f"{_icl:.2f}%", help="Irreversible Capacity Loss during formation. Target <2% for LiCoO₂.")
                if _ce0 is not None:
                    _fc2.metric("CE Cycle 1", f"{_ce0:.2f}%", help="First-cycle CE; ~90–95% is normal — SEI consumes lithium.")
                    _fc3.metric("CE Cycle 3", f"{_ce3:.2f}%", delta=f"+{_ce3-_ce0:.2f}pp", help="CE should stabilise toward 99.9% by cycle 10.")

                if "coulombic_efficiency" in df.columns:
                    _form_plot = df[df["cycle_number"] <= 30].copy()
                    _fig_form = go.Figure()
                    _fig_form.add_trace(go.Scatter(
                        x=_form_plot["cycle_number"].tolist(),
                        y=(_form_plot["coulombic_efficiency"] * 100).tolist(),
                        mode="lines+markers",
                        marker=dict(size=5, color="#48bb78"),
                        line=dict(color="#48bb78", width=2),
                        name="CE",
                        hovertemplate="Cycle %{x}: CE = %{y:.3f}%<extra></extra>",
                    ))
                    _fig_form.add_hline(y=99.9, line_dash="dot", line_color="#f6ad55", annotation_text="99.9% — SEI stabilisation target", annotation_position="bottom right")
                    _fig_form.update_layout(
                        **base_layout(
                            height=260, legend=LEGEND_H,
                            xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                            yaxis=dict(title="Coulombic Efficiency (%)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        ),
                    )
                    _fig_form.update_layout(title=dict(text="CE Stabilisation — Formation Window (First 30 Cycles)", font=dict(size=12, color="#a0aec0"), x=0))
                    st.plotly_chart(_fig_form, use_container_width=True, config={**PLOTLY_CONFIG, "toImageButtonOptions": {**PLOTLY_CONFIG["toImageButtonOptions"], "filename": "ce_formation"}})

                _icl_risk = "Low" if _icl < 1.5 else ("Moderate" if _icl < 3.0 else "High")
                _risk_color = {"Low": "#48bb78", "Moderate": "#f6ad55", "High": "#fc8181"}[_icl_risk]
                _md_html(f"""<div style="background:rgba(26,32,44,0.7);border:1px solid #2d3748;border-radius:8px;padding:12px 16px;font-size:13px"><span style="color:{_risk_color};font-weight:700">ICL Risk: {_icl_risk}</span><span style="color:#a0aec0;margin-left:10px">ICL = {_icl:.2f}% — literature correlation: cells with ICL &lt;1.5% retain &gt;90% SOH beyond 500 cycles (Severson et al. 2019).</span></div>""")
        except Exception as _form_e:
            st.info(f"Formation analysis unavailable: {_form_e}")

    _rate_badge = "◐ SIMULATED" if cell_id in NASA_CELL_IDS else "○ SYNTHETIC"
    with st.expander(f"📊 Rate Capability — {_rate_badge}", expanded=False):
        try:
            import numpy as _np_rate
            _md_html(provenance_banner(
                "simulated" if cell_id in NASA_CELL_IDS else "synthetic",
                "Capacity retention at each C-rate is computed from "
                "<code>Q(C) = Q_nom × SOH × exp(−k_rate × C^1.4)</code>, where k_rate scales "
                "with measured internal resistance. <strong>No multi-rate characterisation test was "
                "performed.</strong> Real rate capability requires dedicated CCCV cycling at each "
                "C-rate on a cell tester (Arbin, Maccor, Neware, etc.)."
            ))
            st.caption(
                "Rate capability shows how much capacity is retained at higher charge/discharge rates. "
                "Capacity drop at 2C vs C/5 quantifies power-fade — critical for EV and fast-charge applications."
            )
            _latest = df.iloc[-1]
            _soh_frac = float(_latest["soh_pct"]) / 100.0
            _r_now    = float(_latest.get("resistance_ohm", 0.150))
            _q_nom    = float(df["capacity_ah"].iloc[0])

            _k_rate    = 0.03 * (_r_now / 0.150)
            _c_rates   = [0.05, 0.10, 0.20, 0.50, 1.0, 2.0, 5.0]
            _c_labels  = ["C/20", "C/10", "C/5", "C/2", "1C", "2C", "5C"]
            _capacities = [_q_nom * _soh_frac * _np_rate.exp(-_k_rate * c ** 1.4) for c in _c_rates]
            _retention  = [100.0 * cap / max(_capacities[0], 1e-9) for cap in _capacities]

            _fig_rate = go.Figure()
            _fig_rate.add_trace(go.Bar(
                x=_c_labels, y=_retention,
                marker_color=["#48bb78" if r >= 90 else "#f6ad55" if r >= 75 else "#fc8181" for r in _retention],
                text=[f"{r:.1f}%" for r in _retention],
                textposition="outside",
                hovertemplate="%{x}: %{y:.1f}% retention<extra></extra>",
            ))
            _fig_rate.update_layout(
                **base_layout(
                    height=280, legend=LEGEND_H,
                    xaxis=dict(title="C-rate", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    yaxis=dict(title="Capacity Retention (%)", range=[0, 115], gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                ),
            )
            _fig_rate.update_layout(title=dict(text="Rate Capability: Capacity Retention at Current SOH", font=dict(size=12, color="#a0aec0"), x=0))
            st.plotly_chart(_fig_rate, use_container_width=True, config={**PLOTLY_CONFIG, "toImageButtonOptions": {**PLOTLY_CONFIG["toImageButtonOptions"], "filename": "rate_capability"}})

            _ret_2c = _retention[5]
            _ret_msg = f"At 2C (fast charge), this cell retains {_ret_2c:.1f}% of its C/5 capacity."
            _ret_color = "#48bb78" if _ret_2c >= 85 else "#f6ad55" if _ret_2c >= 70 else "#fc8181"
            _md_html(f"""<div style="background:rgba(26,32,44,0.7);border:1px solid #2d3748;border-radius:8px;padding:12px 16px;font-size:13px"><span style="color:{_ret_color};font-weight:700">{_ret_msg}</span><span style="color:#a0aec0;margin-left:10px">k_rate = {_k_rate:.3f} (resistance-scaled). >85% at 2C = good fast-charge fitness; &lt;70% = rate-limited application only.</span></div>""")
        except Exception as _rate_e:
            st.info(f"Rate capability analysis unavailable: {_rate_e}")

    _active_chem = st.session_state.get("active_chemistry", "Li-ion (LiCoO₂)")
    if "Li-S" in _active_chem:
        with st.expander("🔋 Li-S Dual Plateau Analysis — ○ SYNTHETIC", expanded=True):
            try:
                import sys as _sys_lis
                import os as _os_lis
                _src = _os_lis.path.join(_os_lis.path.dirname(__file__), "..", "..", "src")
                if _src not in _sys_lis.path:
                    _sys_lis.path.insert(0, _src)
                from lis_model import simulate_lis_vq_curve, lis_degradation_mechanism, generate_lis_cell_data
                import numpy as _np_lis

                _md_html(provenance_banner("synthetic",
                    "The V(Q) dual-plateau curve and shuttle degradation diagnosis are generated by "
                    "<code>lis_model.py</code> using parameterised physics equations. "
                    "<strong>No Li-S cell measurements are connected to this platform.</strong> "
                    "Real Li-S characterisation requires cells from, e.g., Oxis Energy / Lyten / "
                    "Sion Power datasets, with measured plateau capacities and CE from a cell tester."
                ))
                st.caption(
                    "Li-S cells exhibit a dual-plateau discharge: upper plateau (~2.35 V) "
                    "from S₈→Li₂S₄, lower plateau (~2.1 V) from Li₂S₄→Li₂S. "
                    "The polysulfide shuttle reduces CE to 95–99% and accelerates capacity fade."
                )
                _q_now = float(df["capacity_ah"].iloc[-1]) if "capacity_ah" in df.columns else 2.5
                _r_now = float(df["resistance_ohm"].iloc[-1]) if "resistance_ohm" in df.columns else 0.30
                _Q_vq, _V_vq = simulate_lis_vq_curve(_q_now, _r_now)

                _fig_lis = go.Figure()
                _fig_lis.add_trace(go.Scatter(
                    x=_Q_vq.tolist(), y=_V_vq.tolist(),
                    mode="lines", name="V-Q curve",
                    line=dict(color="#f6ad55", width=2.5),
                    hovertemplate="Q = %{x:.3f} Ah, V = %{y:.3f} V<extra></extra>",
                ))
                _fig_lis.add_hrect(y0=2.28, y1=2.45, fillcolor="rgba(246,173,85,0.08)",
                                   line_width=0, annotation_text="Upper plateau (S₈→Li₂S₄)",
                                   annotation_position="top right")
                _fig_lis.add_hrect(y0=2.0,  y1=2.18, fillcolor="rgba(99,179,237,0.08)",
                                   line_width=0, annotation_text="Lower plateau (Li₂S₄→Li₂S)",
                                   annotation_position="bottom right")
                _fig_lis.update_layout(
                    **base_layout(
                        height=300, legend=LEGEND_H,
                        xaxis=dict(title="Capacity (Ah)", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="Voltage (V)", range=[1.8, 2.55], gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                    ),
                )
                _fig_lis.update_layout(title=dict(text="Li-S Dual Plateau Discharge Curve", font=dict(size=12, color="#a0aec0"), x=0))
                st.plotly_chart(_fig_lis, use_container_width=True)

                _lis_df = generate_lis_cell_data(n_cycles=min(len(df), 300), seed=42)
                _mech   = lis_degradation_mechanism(_lis_df)
                _mech_color = "#f6ad55" if "Shuttle" in _mech["mechanism"] else "#fc8181" if "Anode" in _mech["mechanism"] else "#63b3ed"
                _md_html(f"""<div style="background:rgba(26,32,44,0.7);border:1px solid #2d3748;border-radius:8px;padding:12px 16px;font-size:13px"><span style="color:{_mech_color};font-weight:700">{_mech['mechanism']}</span><span style="color:#a0aec0;margin-left:10px">{_mech['explanation']}</span><br><span style="color:#718096;font-size:12px;margin-top:4px;display:block">Confidence: {_mech['confidence']:.0%}</span></div>""")
            except Exception as _lis_e:
                st.info(f"Li-S module unavailable: {_lis_e}")

    elif "SSB" in _active_chem:
        with st.expander("🧱 Solid-State Battery (SSB) Parameters", expanded=True):
            st.caption(
                "SSBs replace liquid electrolyte with a solid ionic conductor. Key differences: "
                "no Warburg diffusion tail in EIS (solid-solid interface), higher interfacial resistance, "
                "no SEI (but solid electrolyte interphase SElI forms), different failure modes (dendrites, delamination)."
            )
            _ssb_c1, _ssb_c2 = st.columns(2)
            _ssb_c1.metric("Electrolyte", "Solid (LLZO / LIPON / sulfide)", help="No liquid electrolyte — eliminates thermal runaway risk from electrolyte combustion.")
            _ssb_c2.metric("EIS signature", "No 45° Warburg tail", help="Solid electrolyte eliminates semi-infinite diffusion. Nyquist shows only high-freq arc.")
            _ssb_c3, _ssb_c4 = st.columns(2)
            _ssb_c3.metric("Interface resistance", "High (0.5–5 Ω·cm²)", help="Solid-solid interface kinetics limit rate capability at low temperature.")
            _ssb_c4.metric("Failure mode", "Dendrite / delamination", help="Li dendrites grow through grain boundaries under high current density. Interfacial delamination from volume change.")
            _md_html("""<div style="background:rgba(26,32,44,0.7);border:1px solid #2d3748;border-radius:8px;padding:12px 16px;font-size:13px;margin-top:8px"><span style="color:#63b3ed;font-weight:700">SSB degradation model not yet implemented</span><span style="color:#a0aec0;margin-left:10px">SSB-specific cycle data (ORNL / Toyota / QuantumScape datasets) required for quantitative analysis. EIS component decomposition will differ: R_SEI replaced by R_SElI (solid electrolyte interphase), no sigma_w Warburg term.</span></div>""")

    # ── Physics-based projection (SPM-inspired) ──
    _md_html(provenance_banner(
        "simulated",
        "Arrhenius + power-law fade model fitted to observed SOH trajectory. "
        "Not a full electrochemical simulation — parameters (A, β, Eₐ) are data-fitted, "
        "not derived from electrode geometry or electrolyte kinetics."
    ))
    with st.expander("Physics-based RUL Projection (SPM-inspired)", expanded=False):
        try:
            from spm_projection import fit_and_project as _fit_and_project

            cyc_arr = df["cycle_number"].values
            soh_arr = df["soh_pct"].values
            temp_c  = float(df["temp_rolling_30cy"].dropna().iloc[-1]) if "temp_rolling_30cy" in df.columns else 25.0
            eol_thr = float(st.session_state.get("eol_threshold_pct", 80.0))

            result = _fit_and_project(cyc_arr, soh_arr, current_temp_c=temp_c, eol_threshold=eol_thr)

            if result is None:
                st.info("Insufficient data for physics-based projection (need ≥10 cycles with SOH data).")
            else:
                # Model quality
                r2_color = "#48bb78" if result.r2 > 0.90 else ("#f6ad55" if result.r2 > 0.75 else "#fc8181")
                st.markdown(
                    f"<div style='font-size:12px;color:#718096;margin-bottom:12px'>"
                    f"Fitted model: SOH(n) = 100 − A·n^β·exp(−Eₐ/kT) &nbsp;·&nbsp; "
                    f"A={result.A:.4f} &nbsp; β={result.beta:.3f} &nbsp; Eₐ={result.Ea_eV:.3f} eV &nbsp;·&nbsp; "
                    f"Fit R² = <strong style='color:{r2_color}'>{result.r2:.3f}</strong></div>",
                    unsafe_allow_html=True,
                )

                COLORS = ["#48bb78", "#63b3ed", "#fc8181"]
                DASH   = ["solid",   "dash",    "dot"]

                fig_spm = go.Figure()
                # Historical trace
                fig_spm.add_trace(go.Scatter(
                    x=cyc_arr, y=soh_arr,
                    name="Observed SOH", mode="lines",
                    line=dict(color="#a0aec0", width=1.5),
                    hovertemplate="Cycle %{x}: %{y:.1f}%<extra>Observed</extra>",
                ))

                for proj, color, dash in zip(result.projections, COLORS, DASH):
                    eol_label = f" → EOL at cycle {proj.eol_cycle}" if proj.eol_cycle else " → EOL beyond projection window"
                    fig_spm.add_trace(go.Scatter(
                        x=proj.cycles, y=proj.soh_pct,
                        name=f"{proj.scenario}{eol_label}",
                        mode="lines",
                        line=dict(color=color, width=2, dash=dash),
                        hovertemplate=f"Cycle %{{x}}: %{{y:.1f}}%<extra>{proj.scenario}</extra>",
                    ))

                fig_spm.add_hline(y=eol_thr, line_dash="dash", line_color="#fc8181", line_width=1,
                                  annotation_text=f"EOL {eol_thr:.0f}%", annotation_position="right")

                fig_spm.update_layout(
                    **base_layout(
                        height=320, legend=LEGEND_H,
                        xaxis=dict(title="Cycle", gridcolor="#232d3b", linecolor="#2d3748", zeroline=False),
                        yaxis=dict(title="SOH (%)", gridcolor="#232d3b", linecolor="#2d3748",
                                   zeroline=False, range=[max(0, eol_thr - 15), 101]),
                    ),
                )
                st.plotly_chart(fig_spm, use_container_width=True, config=PLOTLY_CONFIG)

                # EOL summary table
                eol_rows = []
                for proj in result.projections:
                    if proj.eol_cycle:
                        remaining = proj.eol_cycle - int(cyc_arr[-1])
                        eol_rows.append(f"| {proj.scenario} | {proj.eol_cycle} | {remaining} |")
                if eol_rows:
                    st.markdown(
                        "| Scenario | EOL Cycle | Remaining cycles |\n"
                        "|----------|-----------|------------------|\n" +
                        "\n".join(eol_rows)
                    )

                st.caption(
                    "Projection assumes constant cycling rate and no step-changes in temperature or C-rate. "
                    "Eₐ range for LiCoO₂: 0.3–0.6 eV (SEI-limited); 0.6–0.9 eV (lithium plating). "
                    "Use conservative scenario for high-reliability applications."
                )

        except ImportError:
            st.info("Install scipy to enable physics-based projection.")
        except Exception as _spm_e:
            st.info(f"Physics projection unavailable: {_spm_e}")
